paths:
  trades_csv: ./trades_clean_for_exit_tests.csv
  trade_bars_csv: ./trade_bars.csv
  out_dir: ./exit_out
params:
  time_caps: [6, 8, 10, 12, 15, 20]   # keep for reference, won’t be top when ATR is pinned
  atr_multipliers: [1.25]
